FROM pytorch/pytorch:2.8.0-cuda12.9-cudnn9-devel

RUN apt-get update && apt-get install git vim -yq

COPY requirements.tf.2.19.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

RUN mkdir /.config && chmod -R 777 /.config

# COPY --chmod=777 train.py /opt
# COPY --chmod=777 register.py /opt
COPY --chmod=777 register_full_res.py /opt

ENV TF_ENABLE_ONEDNN_OPTS=0