
FROM tensorflow/tensorflow:2.19.0-gpu
RUN /usr/bin/python3 -m pip install --upgrade pip


RUN apt-get update && apt-get install git vim -yq

COPY requirements.tf.1.19.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

RUN mkdir -p /tmp/.cache/matplotlib && chmod -R 777 /tmp/.cache/matplotlib
ENV MPLCONFIGDIR=/tmp/.cache/matplotlib
ENV TF_ENABLE_ONEDNN_OPTS=0

# COPY --chmod=777 train.py /opt
# COPY --chmod=777 register.py /opt
# COPY --chmod=777 register_full_res.py /opt
